FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

COPY backend.csproj ./
RUN dotnet restore

COPY . .
RUN dotnet publish -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS final
WORKDIR /app
COPY --from=build /app/publish .

ENV ASPNETCORE_URLS=http://0.0.0.0:4000
ENV PORT=4000
EXPOSE 4000

# RUN addgroup -S runner && adduser -S runner -G runner
# USER runner
ENTRYPOINT ["dotnet", "backend.dll"]
